### ISSUE TITLE
f_punchhole for < macos 10.12?

### ISSUE THREAD

**Issue by genevera** [moby/hyperkit#170] opened 2017-12-03 23:32 UTC
Is there a way to get the punchhole headers needed to compile hyperkit onto a < 10.12 system? I was trying to compile the latest master branch today when I ran into the same error described in #160:
```bash
src/lib/block_if.c:275:21: error: variable has incomplete type 'struct fpunchhole'
                struct fpunchhole arg = { .fp_flags = 0, .reserved = 0, .fp_offset = (off_t) fp_offset, .fp_length = (off_t) fp_length };
                                  ^
src/lib/block_if.c:275:10: note: forward declaration of 'struct fpunchhole'
                struct fpunchhole arg = { .fp_flags = 0, .reserved = 0, .fp_offset = (off_t) fp_offset, .fp_length = (off_t) fp_length };
                       ^
src/lib/block_if.c:276:26: error: use of undeclared identifier 'F_PUNCHHOLE'
                ret = fcntl(bc->bc_fd, F_PUNCHHOLE, &arg);
                                       ^
src/lib/block_if.c:713:22: error: variable has incomplete type 'struct fpunchhole'
                        struct fpunchhole arg = { .fp_flags = 0, .reserved = 0, .fp_offset = 0, .fp_length = 0 };
                                          ^
src/lib/block_if.c:713:11: note: forward declaration of 'struct fpunchhole'
                        struct fpunchhole arg = { .fp_flags = 0, .reserved = 0, .fp_offset = 0, .fp_length = 0 };
                               ^
src/lib/block_if.c:714:18: error: use of undeclared identifier 'F_PUNCHHOLE'
                        if (fcntl(fd, F_PUNCHHOLE, &arg) == 0) {
                                      ^
4 errors generated.
make: *** [build/lib/block_if.o] Error 1
cc src/lib/block_if.c
```

**Comment by justincormack** [comment] 2017-12-03 23:43
It is not supported on previous versions. You could hack around it I
guess...

**Comment by genevera** [comment] 2017-12-04 00:08
That's what I did :).  I checked out the version of `block_if.c` before the pr was merged and it compiled fine.

**Comment by ijc** [comment] 2017-12-04 11:06
AIUI from when this is added the important factor is the version of xcode (for the headers), not the version of the OS. Can you try the latest xcode please.

Closing as a duplicate of #160.

**Closed by ijc** 2017-12-04 11:06 UTC

**Comment by genevera** [comment] 2017-12-04 23:16
@ijc I did try that initially. Unfortunately the latest Xcode does not install on El Capitan.

**Comment by wmertens** [comment] 2018-12-04 10:43
macOS just keeps getting worse 😞
